---
- name: Удаление старых пакетов Docker
  ansible.builtin.apt:
    name:
      - containerd
      - docker
      - docker-engine
      - docker.io
      - runc
    state: absent
  become: yes

- name: Очистка старых ключей и репозиториев Docker
  block:
    - name: Удаление ключей Docker
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/keyrings/docker.asc
        - /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Удаление файлов репозитория
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/docker.list"
        state: absent
  become: yes

- name: Установка системных пакетов
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - python3-pip
      - lsb-release
    state: present
    update_cache: yes
    cache_valid_time: 86400
  become: yes

- name: Добавление репозитория Universe
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
    state: present
  become: yes

- name: Обновление кеша APT
  ansible.builtin.apt:
    update_cache: yes
  become: yes


- name: Создание директории для ключей
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: 0755
  become: yes

- name: Добавление GPG-ключа Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes

- name: Проверка прав ключа Docker
  ansible.builtin.file:
    path: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: 0644
  become: yes

- name: Пауза для применения изменений
  ansible.builtin.pause:
    seconds: 5

- name: Добавление Docker репозитория
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker-ce
    state: present
    mode: 0644
    update_cache: yes
  become: yes

- name: Установка Docker CE
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
    state: present
    update_cache: yes
  become: yes

- name: Запуск и активация Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Установка Docker Compose
  block:
    - name: Получение последней версии
      ansible.builtin.uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: compose_version
      become: yes

    - name: Скачивание бинарника
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version.json.tag_name }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755
      become: yes

- name: Добавление пользователя в группу docker
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Создание рабочих директорий
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /opt/app/nginx-conf
    - /opt/app/html
  become: yes

- name: Развертывание конфигураций
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: "docker-compose.yaml", dest: "/opt/app/docker-compose.yaml" }
    - { src: "nginx-conf/nginx.conf", dest: "/opt/app/nginx-conf/nginx.conf" }
    - { src: "html/index.html", dest: "/opt/app/html/index.html" }
    - { src: "html/index2.html", dest: "/opt/app/html/index2.html" }
  become: yes

- name: Запуск docker-compose
  ansible.builtin.command:
    cmd: docker-compose -f /opt/app/docker-compose.yaml up -d
    chdir: /opt/app
  become: yes