version: '3'

services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - app1
      - app2

  app1:
    image: nginx:latest
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
    networks:
      - app_network
    expose:
      - "80"

  app2:
    image: nginx:latest
    volumes:
      - ./html/index2.html:/usr/share/nginx/html/index.html
    networks:
      - app_network
    expose:
      - "80"

networks:
  app_network: